version: '3.8'

services:
  app:
    build:
      context: .
      network: host
    volumes:
      - /home/runner/vosk-model-ru-0.42:/models/vosk-model-ru-0.42:ro
    container_name: worker-container
    ports:
      - "127.0.0.1:3005:3005"
    environment:
      - WORKERS=${WORKERS}
      - QUEUE_KEY=${QUEUE_KEY}
      - REDIS_URL=${REDIS_URL}
      - PROCESSING_KEY=${PROCESSING_KEY }
      - DLQ_KEY=${DLQ_KEY }
      - BLOCK_SEC=${BLOCK_SEC }
      - MAX_ATTEMPTS=${MAX_ATTEMPTS }
      - ATTEMPTS_HASH=${ATTEMPTS_HASH }
      - REQUEUE_ON_START=${REQUEUE_ON_START }
      - MODEL_PATH=${MODEL_PATH }
      - SAMPLE_RATE=${SAMPLE_RATE }
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - pray_rep_app_network

networks:
  pray_rep_app_network:
    external: true