services:
  redis:
    image: redis:alpine
    container_name: redis-container
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    environment:
      REDIS_PASSWORD: password
      REDIS_USER: admin
      REDIS_USER_PASSWORD: hgiuhdfgipudhfidfug
    command: redis-server --requirepass password
    volumes:
      - redis_data:/data
    networks:
      - pray_rep_app_network
volumes:
  redis_data:
    driver: local
networks:
  pray_rep_app_network:
    driver: bridge
